# Setup
title:               FidelisFactory
tagline:             'Simple digitale Lösungen, um den Alltag zu erleichtern'
description:         'Interesse unsere Apps zu verbessern? Melde dich bei uns via info@fidelisfactory.ch'
url:                 https://fidelisfactory.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
markdown:            kramdown

# About/contact
author:
  name:              FidelisFactory
  url:               https://github.com/fidelisFactory

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
